### ISSUE TITLE
CheckCompileLinkOption fails when Xcode compiler is invoked from command line

### ISSUE THREAD

**Issue by aciereszko** [noloader/cryptopp-cmake#41]
When testing for the compiler capabilities with:

    CheckCompileLinkOption("-msse2" CRYPTOPP_IA32_SSE2 "${TEST_PROG_DIR}/test_x86_sse2.cxx")

`CheckCompileLinkOption` invokes the `CMAKE_CXX_COMPILER` directly and compiles the test file. This file will fail to compile with an error message that it can't locate `stdlib.h`, when the compiler is clang from the xcode toolchain. Try to run:

    /Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -msse2 test_x86_sse2.cxx

This is the error:
```
In file included from test_x86_sse2.cxx:1:
In file included from /Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:27:
In file included from /Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/xmmintrin.h:39:
In file included from /Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/mm_malloc.h:27:
/Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
```

However as soon as you add the `-isysroot` pointing to the correct sysroot, compiles without a problem.

This seems to be a problem with the compilers in this path in the toolchain, the clang in `/usr/bin/` works fine.

So, there should be a way to modify `CmakeLists` to take the sysroot into account, but I'm not sure what would be the elegant way to do that...

**Comment by noloader** [comment]
Thanks @aciereszko.

Please show how you are invoking CMake. I think you need to set some options like:

    export CXX=/Applications/Xcode9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    cmake <source dir> -DCMAKE_CXX_COMPILER="$CXX"

We cut-in [`CheckCompileLinkOption`](https://github.com/noloader/cryptopp-cmake/blob/master/CMakeLists.txt#L222) recently and it uses `CXXFLAGS`. You should be able to use `--sysroot` if needed:

```
function(CheckCompileLinkOption opt var prog)

    message(STATUS "Performing Test ${var}")
    execute_process(
      COMMAND sh -c "${CMAKE_CXX_COMPILER} ${CMAKE_CXX_FLAGS} ${opt} ${prog} 2>&1"
      RESULT_VARIABLE COMMAND_RESULT
      OUTPUT_VARIABLE COMMAND_OUTPUT
      OUTPUT_STRIP_TRAILING_WHITESPACE)
  ...

endfunction(CheckCompileLinkOption)
```

There is also a related problem that we can't get CMake to stop using the C compiler. I believe it is due to a handful of CMake bugs. I believe [`project`](https://cmake.org/cmake/help/v3.0/command/project.html) is the recommended way, but I've never been able to get `project(cryptopp CXX)` to work as expected. It fails to work as expected on Solaris and PowerPC. I've also tried to set the C compiler to the C++ compiler in [`CMakeList.txt : 8`](https://github.com/noloader/cryptopp-cmake/blob/master/CMakeLists.txt#L8), but CMake fails the build claiming the C compiler is a C++ compiler:

```
# Should we be setting things like this? We are not a C project
# so nothing should be done with the C compiler. But there is
# no reliable way to tell CMake we are C++.
# Cannot set this... Breaks Linux PowerPC with Clang:
# SET(CMAKE_C_COMPILER ${CMAKE_CXX_COMPILER})
# # error "The CMAKE_C_COMPILER is set to a C++ compiler"
```

**Comment by aciereszko** [comment]
To be honest I am not sure when cmake sets the CMAKE_CXX_FLAGS, but from what I understand you are saying that at the time you are executing the shell command to compile the test cxx files you would expect CMAKE_CXX_FLAGS to contain the -isysroot flag? I will have to do some digging around to see what is happening.

The interesting part is that if I use the /usr/bin/clang that test cxx file compiles without the need to add the -isysroot flag but when I use the clang from the xcode toolchain location it does not (I dumped the command from your cmakelists file with a message statement and ran it in terminal).

Anyway no need to apologize, I suspect I am doing something wrong, you guys are doing great work!

**Comment by mouse07410** [comment]
My suggestion is within CMakeLists.txt check for OS, and if it's MacOS set SYSROOT to output of xcrun --sdk-path. I'll post details when I get to my computer, but it's pretty simple (unlike many things with CMake).

**Comment by noloader** [comment]
@mouse07410 ,

What is the common case among developers when using Xcode? Do developers bounce around with different compilers from the SDK? Or do they set the default and stick to one compiler from the SDK?

I ask because I don't ever recall setting a SDK path. I usually just use a compiler from the toolchain of interest or the default one. In fact, we bounce around SDKs in [`setenv-ios.sh`](https://github.com/weidai11/cryptopp/blob/master/TestScripts/setenv-ios.sh) (though we set a `--sysroot`).

In fact it looks like we usually use the default toolchain at [line 166](https://github.com/weidai11/cryptopp/blob/master/TestScripts/setenv-ios.sh#L166) and then build a sysroot like `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk` around [line 180](https://github.com/weidai11/cryptopp/blob/master/TestScripts/setenv-ios.sh#L179).

**Comment by aciereszko** [comment]
There is an easy for way for you guys to reproduce this problem. On macos, you can download CLion, and load your cmake project (follow your directions to get the cryptopp repo and drop your two cmake files).

Open the project and CLion will run cmake and you will see the Tests fail. You will need to have XCode installed, and xcode-select install is run, to install the command lines. Verify that cmake is using the compiler from the xcode toolchain.

![image](https://user-images.githubusercontent.com/5295282/49711050-2a573c00-fc0b-11e8-9510-153f510f1aaf.png)

Or you can just run the command the CLion is using without installing it, I get the same error (the output above is actually from that):

cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" <cryptopp_path>

I'm not sure why CLion uses the CodeBlocks generator, but the problem is the same using the "Unix Makefiles" generator as well.

Not sure if this is helpful at all, I appreciate your guys' time and effort here.

**Comment by noloader** [comment]
> Not sure if this is helpful at all...

I think the problem is with `CheckCompileOption` and `CheckCompileLinkOption`:

```
function(CheckCompileLinkOption opt var prog)

    message(STATUS "Performing Test ${var}")
    execute_process(
      COMMAND sh -c "${CMAKE_CXX_COMPILER} ${CMAKE_CXX_FLAGS} ${opt} ${prog} 2>&1"
      RESULT_VARIABLE COMMAND_RESULT
      OUTPUT_VARIABLE COMMAND_OUTPUT
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    ...

endfunction(CheckCompileLinkOption)
```

We use the CMake specific variables `CMAKE_CXX_COMPILER` and `CMAKE_CXX_FLAGS`. Maybe there is another CMake-specific `CXXFLAGS` we should be using.

In any case CMake has to give us the C++ flags and options for the project. It has to provide them to us for feature testing.

------

And to be clear, the feature testing is compiler feature testing. We need to know if a compiler supports, say, the SHA instructions. So we need to test for `-msha` on x86, `-mcpu=power8 -maltivec` on PowerPC and `-march=armv8-a+crypto` on Aarch64.

We don't care about the actual cpu features at build time. We use that at runtime. If a cpu feature is available at runtime then we use it (Intel calls this dynamic dispatching). Otherwise we use other code, like straight C++ code.

Here's a typical rule from the [makefile](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L1481). `SHA_FLAG` will have the additional flags or it will be empty. All the build systems work the same way. They just do it in different ways.

````
sha_simd.o : sha_simd.cpp
    $(CXX) $(strip $(CXXFLAGS) $(SHA_FLAG) -c) $<
```

**Comment by aciereszko** [comment]
Just verified that the same error happens with the XCode cmake generator.

**Comment by mouse07410** [comment]
@noloader in my experience, usually one compiler is used fur most of the development, and other compilers/toolchains - only if/when necessary fur some reason (typically when checking portability, or trying to work around a showstopper bug in the "main" toolchain).

**Comment by aciereszko** [comment]
In my case three are useful in daily work, xcode macos toolchain for development (test app, unit tests etc) this is 80% of dev, xcode ios toolchain for actually testing the app out on device, I would say 10% of dev and the windows vs toolchain which usually gets used in spurts (when working on some particular issue in windows, or when testing) so this I would say less often than the other too on daily work, but when it does it may be for a few days at a time.

**Comment by aciereszko** [comment]
Hi, just wondering, were you able to reproduce the problem, building just vanilla cryptopp with your CMakeLists file, on a mac using xcode toolchain with the Unix Makefiles generator?

**Comment by noloader** [comment]
This is now officially CMake's problem: [CXX and CXXFLAGS used during feature tests are not accurate in CmakeList.txt](https://gitlab.kitware.com/cmake/cmake/issues/18813).

When the CMake folks come back with a work around I will add it to our `CmakeList.txt`.
